name: DockerFile-to-image
on: pull
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build -t ubuntu:1.0 .
      - name: push image
        run: |
          docker login -u vinodo3735 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker tag ubuntu:1.0 vinodo3735/ubuntu:1.0
          docker push vinodo3735/ubuntu:1.0
      

      
    
