name: DockerFile-to-image
on: 
  push:
    branches:
      - main:
    paths:
      - 'dockerfile'
jobs:
  publish_images:
    runs-ob: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build dockerfile .
      

      
    
