name: DockerFile-to-image
on: push
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build -t ubuntuimg .
      - name: push image
        run: |
          docker login -u vinodo3735 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ubuntuimg:latest 
      

      
    
